//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composite.StandardPlugins.WebClient.WebRequestHandlers.LoginWebRequestHandler.Resources
{
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed class LoginHandlerResources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        private LoginHandlerResources() {
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Composite.StandardPlugins.WebClient.WebRequestHandlers.LoginWebRequestHandler.Resources.LoginHandlerRes" +
                            "ources", typeof(LoginHandlerResources).Assembly);
                    _resourceManager = temp;
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Login to {0}'.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Login'.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Incorrect user name or password'.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Password'.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Username'.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Login to {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string HeaderFormat(object arg0) {
            return string.Format(_resourceCulture, Header, arg0);
        }
    }
}
