//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composite.Core.PackageSystem.WebServiceClient
{
    using System.Runtime.Serialization;
    using System;


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "LicenseDefinitionDescriptor", Namespace = "http://www.composite.net/ns/managemen")]
    [System.SerializableAttribute()]
    public partial class LicenseDefinitionDescriptor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid InstallationIdField;

        private System.Guid ProductIdField;

        private bool PermanentField;

        private System.DateTime ExpiresField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseKeyField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Guid InstallationId
        {
            get
            {
                return this.InstallationIdField;
            }
            set
            {
                if ((this.InstallationIdField.Equals(value) != true))
                {
                    this.InstallationIdField = value;
                    this.RaisePropertyChanged("InstallationId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Guid ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                if ((this.ProductIdField.Equals(value) != true))
                {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public bool Permanent
        {
            get
            {
                return this.PermanentField;
            }
            set
            {
                if ((this.PermanentField.Equals(value) != true))
                {
                    this.PermanentField = value;
                    this.RaisePropertyChanged("Permanent");
                }
            }
        }


        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public System.DateTime Expires
        {
            get
            {
                return this.ExpiresField;
            }
            set
            {
                if ((this.ExpiresField.Equals(value) != true))
                {
                    this.ExpiresField = value;
                    this.RaisePropertyChanged("Expires");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string LicenseKey
        {
            get
            {
                return this.LicenseKeyField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LicenseKeyField, value) != true))
                {
                    this.LicenseKeyField = value;
                    this.RaisePropertyChanged("LicenseKey");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }



    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.composite.net/ns/managemen", ConfigurationName = "Composite.Core.PackageSystem.WebServiceClient.LicenseDefinitionServiceSoap")]
    public interface LicenseDefinitionServiceSoap
    {

        // CODEGEN: Generating message contract since element name publicKeyXml from namespace http://www.composite.net/ns/managemen is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.composite.net/ns/managemen/ValidateTrialLicenseDefinitionRequest", ReplyAction = "*")]
        Composite.Core.PackageSystem.WebServiceClient.ValidateTrialLicenseDefinitionRequestResponse ValidateTrialLicenseDefinitionRequest(Composite.Core.PackageSystem.WebServiceClient.ValidateTrialLicenseDefinitionRequestRequest request);

        // CODEGEN: Generating message contract since element name publicKeyXml from namespace http://www.composite.net/ns/managemen is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.composite.net/ns/managemen/GetTrialLicenseDefinition", ReplyAction = "*")]
        Composite.Core.PackageSystem.WebServiceClient.GetTrialLicenseDefinitionResponse GetTrialLicenseDefinition(Composite.Core.PackageSystem.WebServiceClient.GetTrialLicenseDefinitionRequest request);
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ValidateTrialLicenseDefinitionRequestRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ValidateTrialLicenseDefinitionRequest", Namespace = "http://www.composite.net/ns/managemen", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.ValidateTrialLicenseDefinitionRequestRequestBody Body;

        public ValidateTrialLicenseDefinitionRequestRequest()
        {
        }

        public ValidateTrialLicenseDefinitionRequestRequest(Composite.Core.PackageSystem.WebServiceClient.ValidateTrialLicenseDefinitionRequestRequestBody Body)
        {
            this.Body = Body;
        }
    }



    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.composite.net/ns/managemen")]
    public partial class ValidateTrialLicenseDefinitionRequestRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public System.Guid installationId;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Guid productId;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string publicKeyXml;

        public ValidateTrialLicenseDefinitionRequestRequestBody()
        {
        }

        public ValidateTrialLicenseDefinitionRequestRequestBody(System.Guid installationId, System.Guid productId, string publicKeyXml)
        {
            this.installationId = installationId;
            this.productId = productId;
            this.publicKeyXml = publicKeyXml;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ValidateTrialLicenseDefinitionRequestResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ValidateTrialLicenseDefinitionRequestResponse", Namespace = "http://www.composite.net/ns/managemen", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.ValidateTrialLicenseDefinitionRequestResponseBody Body;

        public ValidateTrialLicenseDefinitionRequestResponse()
        {
        }

        public ValidateTrialLicenseDefinitionRequestResponse(Composite.Core.PackageSystem.WebServiceClient.ValidateTrialLicenseDefinitionRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.composite.net/ns/managemen")]
    public partial class ValidateTrialLicenseDefinitionRequestResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string ValidateTrialLicenseDefinitionRequestResult;

        public ValidateTrialLicenseDefinitionRequestResponseBody()
        {
        }

        public ValidateTrialLicenseDefinitionRequestResponseBody(string ValidateTrialLicenseDefinitionRequestResult)
        {
            this.ValidateTrialLicenseDefinitionRequestResult = ValidateTrialLicenseDefinitionRequestResult;
        }
    }




    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetTrialLicenseDefinitionRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetTrialLicenseDefinition", Namespace = "http://www.composite.net/ns/managemen", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.GetTrialLicenseDefinitionRequestBody Body;

        public GetTrialLicenseDefinitionRequest()
        {
        }

        public GetTrialLicenseDefinitionRequest(Composite.Core.PackageSystem.WebServiceClient.GetTrialLicenseDefinitionRequestBody Body)
        {
            this.Body = Body;
        }
    }





    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.composite.net/ns/managemen")]
    public partial class GetTrialLicenseDefinitionRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public System.Guid installationId;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Guid productId;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string publicKeyXml;

        public GetTrialLicenseDefinitionRequestBody()
        {
        }

        public GetTrialLicenseDefinitionRequestBody(System.Guid installationId, System.Guid productId, string publicKeyXml)
        {
            this.installationId = installationId;
            this.productId = productId;
            this.publicKeyXml = publicKeyXml;
        }
    }




    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetTrialLicenseDefinitionResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetTrialLicenseDefinitionResponse", Namespace = "http://www.composite.net/ns/managemen", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.GetTrialLicenseDefinitionResponseBody Body;

        public GetTrialLicenseDefinitionResponse()
        {
        }

        public GetTrialLicenseDefinitionResponse(Composite.Core.PackageSystem.WebServiceClient.GetTrialLicenseDefinitionResponseBody Body)
        {
            this.Body = Body;
        }
    }



    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://www.composite.net/ns/managemen")]
    public partial class GetTrialLicenseDefinitionResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.LicenseDefinitionDescriptor GetTrialLicenseDefinitionResult;

        public GetTrialLicenseDefinitionResponseBody()
        {
        }

        public GetTrialLicenseDefinitionResponseBody(Composite.Core.PackageSystem.WebServiceClient.LicenseDefinitionDescriptor GetTrialLicenseDefinitionResult)
        {
            this.GetTrialLicenseDefinitionResult = GetTrialLicenseDefinitionResult;
        }
    }



    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LicenseDefinitionServiceSoapChannel : Composite.Core.PackageSystem.WebServiceClient.LicenseDefinitionServiceSoap, System.ServiceModel.IClientChannel
    {
    }



    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LicenseDefinitionServiceSoapClient : System.ServiceModel.ClientBase<Composite.Core.PackageSystem.WebServiceClient.LicenseDefinitionServiceSoap>, Composite.Core.PackageSystem.WebServiceClient.LicenseDefinitionServiceSoap
    {

        public LicenseDefinitionServiceSoapClient()
        {
        }

        public LicenseDefinitionServiceSoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public LicenseDefinitionServiceSoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public LicenseDefinitionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public LicenseDefinitionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.ValidateTrialLicenseDefinitionRequestResponse Composite.Core.PackageSystem.WebServiceClient.LicenseDefinitionServiceSoap.ValidateTrialLicenseDefinitionRequest(Composite.Core.PackageSystem.WebServiceClient.ValidateTrialLicenseDefinitionRequestRequest request)
        {
            return base.Channel.ValidateTrialLicenseDefinitionRequest(request);
        }

        public string ValidateTrialLicenseDefinitionRequest(System.Guid installationId, System.Guid productId, string publicKeyXml)
        {
            Composite.Core.PackageSystem.WebServiceClient.ValidateTrialLicenseDefinitionRequestRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.ValidateTrialLicenseDefinitionRequestRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.ValidateTrialLicenseDefinitionRequestRequestBody();
            inValue.Body.installationId = installationId;
            inValue.Body.productId = productId;
            inValue.Body.publicKeyXml = publicKeyXml;
            Composite.Core.PackageSystem.WebServiceClient.ValidateTrialLicenseDefinitionRequestResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.LicenseDefinitionServiceSoap)(this)).ValidateTrialLicenseDefinitionRequest(inValue);
            return retVal.Body.ValidateTrialLicenseDefinitionRequestResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.GetTrialLicenseDefinitionResponse Composite.Core.PackageSystem.WebServiceClient.LicenseDefinitionServiceSoap.GetTrialLicenseDefinition(Composite.Core.PackageSystem.WebServiceClient.GetTrialLicenseDefinitionRequest request)
        {
            return base.Channel.GetTrialLicenseDefinition(request);
        }

        public Composite.Core.PackageSystem.WebServiceClient.LicenseDefinitionDescriptor GetTrialLicenseDefinition(System.Guid installationId, System.Guid productId, string publicKeyXml)
        {
            Composite.Core.PackageSystem.WebServiceClient.GetTrialLicenseDefinitionRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.GetTrialLicenseDefinitionRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.GetTrialLicenseDefinitionRequestBody();
            inValue.Body.installationId = installationId;
            inValue.Body.productId = productId;
            inValue.Body.publicKeyXml = publicKeyXml;
            Composite.Core.PackageSystem.WebServiceClient.GetTrialLicenseDefinitionResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.LicenseDefinitionServiceSoap)(this)).GetTrialLicenseDefinition(inValue);
            return retVal.Body.GetTrialLicenseDefinitionResult;
        }
    }
}
