//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591
namespace Composite.Core.PackageSystem.WebServiceClient
{
    using System.Runtime.Serialization;
    using System;


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PackageDescriptor", Namespace = "http://package.composite.net/package.asmx")]
    [System.SerializableAttribute()]
    public partial class PackageDescriptor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid IdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageVersionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechicalDetailsField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsoleBrowserUrlField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReadMoreUrlField;

        private bool IsTrialField;

        private System.Nullable<int> TrialPeriodDaysField;

        private bool IsFreeField;

        private bool InstallationRequireLicenseFileUpdateField;

        private decimal PriceAmmountField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceCurrencyField;

        private bool UpgradeAgreementMandatoryField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MinCompositeVersionSupportedField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaxCompositeVersionSupportedField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Composite.Core.PackageSystem.WebServiceClient.PackageReference[] RequiredPackagesField;

        private System.Guid EulaIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageFileDownloadUrlField;

        private System.Guid LicenseIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CultureField;

        private System.Guid UserIdField;

        private bool OnlineField;

        private bool SubscriptionOnlyField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Composite.Core.PackageSystem.WebServiceClient.SubscriptionDescriptor[] SubscriptionsField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                if ((this.IdField.Equals(value) != true))
                {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true))
                {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NameField, value) != true))
                {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string PackageVersion
        {
            get
            {
                return this.PackageVersionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PackageVersionField, value) != true))
                {
                    this.PackageVersionField = value;
                    this.RaisePropertyChanged("PackageVersion");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AuthorField, value) != true))
                {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true))
                {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string TechicalDetails
        {
            get
            {
                return this.TechicalDetailsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TechicalDetailsField, value) != true))
                {
                    this.TechicalDetailsField = value;
                    this.RaisePropertyChanged("TechicalDetails");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string ConsoleBrowserUrl
        {
            get
            {
                return this.ConsoleBrowserUrlField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ConsoleBrowserUrlField, value) != true))
                {
                    this.ConsoleBrowserUrlField = value;
                    this.RaisePropertyChanged("ConsoleBrowserUrl");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string ReadMoreUrl
        {
            get
            {
                return this.ReadMoreUrlField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ReadMoreUrlField, value) != true))
                {
                    this.ReadMoreUrlField = value;
                    this.RaisePropertyChanged("ReadMoreUrl");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 9)]
        public bool IsTrial
        {
            get
            {
                return this.IsTrialField;
            }
            set
            {
                if ((this.IsTrialField.Equals(value) != true))
                {
                    this.IsTrialField = value;
                    this.RaisePropertyChanged("IsTrial");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 10)]
        public System.Nullable<int> TrialPeriodDays
        {
            get
            {
                return this.TrialPeriodDaysField;
            }
            set
            {
                if ((this.TrialPeriodDaysField.Equals(value) != true))
                {
                    this.TrialPeriodDaysField = value;
                    this.RaisePropertyChanged("TrialPeriodDays");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 11)]
        public bool IsFree
        {
            get
            {
                return this.IsFreeField;
            }
            set
            {
                if ((this.IsFreeField.Equals(value) != true))
                {
                    this.IsFreeField = value;
                    this.RaisePropertyChanged("IsFree");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 12)]
        public bool InstallationRequireLicenseFileUpdate
        {
            get
            {
                return this.InstallationRequireLicenseFileUpdateField;
            }
            set
            {
                if ((this.InstallationRequireLicenseFileUpdateField.Equals(value) != true))
                {
                    this.InstallationRequireLicenseFileUpdateField = value;
                    this.RaisePropertyChanged("InstallationRequireLicenseFileUpdate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 13)]
        public decimal PriceAmmount
        {
            get
            {
                return this.PriceAmmountField;
            }
            set
            {
                if ((this.PriceAmmountField.Equals(value) != true))
                {
                    this.PriceAmmountField = value;
                    this.RaisePropertyChanged("PriceAmmount");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 14)]
        public string PriceCurrency
        {
            get
            {
                return this.PriceCurrencyField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PriceCurrencyField, value) != true))
                {
                    this.PriceCurrencyField = value;
                    this.RaisePropertyChanged("PriceCurrency");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 15)]
        public bool UpgradeAgreementMandatory
        {
            get
            {
                return this.UpgradeAgreementMandatoryField;
            }
            set
            {
                if ((this.UpgradeAgreementMandatoryField.Equals(value) != true))
                {
                    this.UpgradeAgreementMandatoryField = value;
                    this.RaisePropertyChanged("UpgradeAgreementMandatory");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 16)]
        public string MinCompositeVersionSupported
        {
            get
            {
                return this.MinCompositeVersionSupportedField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MinCompositeVersionSupportedField, value) != true))
                {
                    this.MinCompositeVersionSupportedField = value;
                    this.RaisePropertyChanged("MinCompositeVersionSupported");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 17)]
        public string MaxCompositeVersionSupported
        {
            get
            {
                return this.MaxCompositeVersionSupportedField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MaxCompositeVersionSupportedField, value) != true))
                {
                    this.MaxCompositeVersionSupportedField = value;
                    this.RaisePropertyChanged("MaxCompositeVersionSupported");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 18)]
        public Composite.Core.PackageSystem.WebServiceClient.PackageReference[] RequiredPackages
        {
            get
            {
                return this.RequiredPackagesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RequiredPackagesField, value) != true))
                {
                    this.RequiredPackagesField = value;
                    this.RaisePropertyChanged("RequiredPackages");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 19)]
        public System.Guid EulaId
        {
            get
            {
                return this.EulaIdField;
            }
            set
            {
                if ((this.EulaIdField.Equals(value) != true))
                {
                    this.EulaIdField = value;
                    this.RaisePropertyChanged("EulaId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 20)]
        public string PackageFileDownloadUrl
        {
            get
            {
                return this.PackageFileDownloadUrlField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PackageFileDownloadUrlField, value) != true))
                {
                    this.PackageFileDownloadUrlField = value;
                    this.RaisePropertyChanged("PackageFileDownloadUrl");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 21)]
        public System.Guid LicenseId
        {
            get
            {
                return this.LicenseIdField;
            }
            set
            {
                if ((this.LicenseIdField.Equals(value) != true))
                {
                    this.LicenseIdField = value;
                    this.RaisePropertyChanged("LicenseId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 22)]
        public string Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CultureField, value) != true))
                {
                    this.CultureField = value;
                    this.RaisePropertyChanged("Culture");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 23)]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                if ((this.UserIdField.Equals(value) != true))
                {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 24)]
        public bool Online
        {
            get
            {
                return this.OnlineField;
            }
            set
            {
                if ((this.OnlineField.Equals(value) != true))
                {
                    this.OnlineField = value;
                    this.RaisePropertyChanged("Online");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 25)]
        public bool SubscriptionOnly
        {
            get
            {
                return this.SubscriptionOnlyField;
            }
            set
            {
                if ((this.SubscriptionOnlyField.Equals(value) != true))
                {
                    this.SubscriptionOnlyField = value;
                    this.RaisePropertyChanged("SubscriptionOnly");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 26)]
        public Composite.Core.PackageSystem.WebServiceClient.SubscriptionDescriptor[] Subscriptions
        {
            get
            {
                return this.SubscriptionsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SubscriptionsField, value) != true))
                {
                    this.SubscriptionsField = value;
                    this.RaisePropertyChanged("Subscriptions");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PackageReference", Namespace = "http://package.composite.net/package.asmx")]
    [System.SerializableAttribute()]
    public partial class PackageReference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid IdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                if ((this.IdField.Equals(value) != true))
                {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NameField, value) != true))
                {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SubscriptionDescriptor", Namespace = "http://package.composite.net/package.asmx")]
    [System.SerializableAttribute()]
    public partial class SubscriptionDescriptor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid IdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsUrlField;

        private bool PurchasableField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                if ((this.IdField.Equals(value) != true))
                {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NameField, value) != true))
                {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string DetailsUrl
        {
            get
            {
                return this.DetailsUrlField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DetailsUrlField, value) != true))
                {
                    this.DetailsUrlField = value;
                    this.RaisePropertyChanged("DetailsUrl");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public bool Purchasable
        {
            get
            {
                return this.PurchasableField;
            }
            set
            {
                if ((this.PurchasableField.Equals(value) != true))
                {
                    this.PurchasableField = value;
                    this.RaisePropertyChanged("Purchasable");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://package.composite.net/package.asmx", ConfigurationName = "Core.PackageSystem.WebServiceClient.PackagesSoap")]
    public interface PackagesSoap
    {

        // CODEGEN: Generating message contract since element name Culture from namespace http://package.composite.net/package.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/GetPackageList", ReplyAction = "*")]
        Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponse GetPackageList(Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/GetPackageList", ReplyAction = "*")]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponse> GetPackageListAsync(Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/IsOperational", ReplyAction = "*")]
        bool IsOperational();

        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/IsOperational", ReplyAction = "*")]
        System.Threading.Tasks.Task<bool> IsOperationalAsync();

        // CODEGEN: Generating message contract since element name userCulture from namespace http://package.composite.net/package.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/GetEulaText", ReplyAction = "*")]
        Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponse GetEulaText(Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/GetEulaText", ReplyAction = "*")]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponse> GetEulaTextAsync(Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequest request);

        // CODEGEN: Generating message contract since element name localUserName from namespace http://package.composite.net/package.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/RegisterPackageUninstall", ReplyAction = "*")]
        Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponse RegisterPackageUninstall(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/RegisterPackageUninstall", ReplyAction = "*")]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponse> RegisterPackageUninstallAsync(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequest request);

        // CODEGEN: Generating message contract since element name packageName from namespace http://package.composite.net/package.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/PackageActivity", ReplyAction = "*")]
        Composite.Core.PackageSystem.WebServiceClient.PackageActivityResponse PackageActivity(Composite.Core.PackageSystem.WebServiceClient.PackageActivityRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/PackageActivity", ReplyAction = "*")]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.PackageActivityResponse> PackageActivityAsync(Composite.Core.PackageSystem.WebServiceClient.PackageActivityRequest request);

        // CODEGEN: Generating message contract since element name localUserName from namespace http://package.composite.net/package.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/RequestLicenseUpdate", ReplyAction = "*")]
        Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateResponse RequestLicenseUpdate(Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/RequestLicenseUpdate", ReplyAction = "*")]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateResponse> RequestLicenseUpdateAsync(Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateRequest request);

        // CODEGEN: Generating message contract since element name LocalUserName from namespace http://package.composite.net/package.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/RegisterPackageInstallationCompletion", ReplyAction = "*")]
        Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponse RegisterPackageInstallationCompletion(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/RegisterPackageInstallationCompletion", ReplyAction = "*")]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponse> RegisterPackageInstallationCompletionAsync(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequest request);

        // CODEGEN: Generating message contract since element name LocalUserName from namespace http://package.composite.net/package.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/RegisterPackageInstallationFailure", ReplyAction = "*")]
        Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponse RegisterPackageInstallationFailure(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://package.composite.net/package.asmx/RegisterPackageInstallationFailure", ReplyAction = "*")]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponse> RegisterPackageInstallationFailureAsync(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetPackageListRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetPackageList", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequestBody Body;

        public GetPackageListRequest()
        {
        }

        public GetPackageListRequest(Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://package.composite.net/package.asmx")]
    public partial class GetPackageListRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public System.Guid InstallationId;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Culture;

        public GetPackageListRequestBody()
        {
        }

        public GetPackageListRequestBody(System.Guid InstallationId, string Culture)
        {
            this.InstallationId = InstallationId;
            this.Culture = Culture;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetPackageListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetPackageListResponse", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponseBody Body;

        public GetPackageListResponse()
        {
        }

        public GetPackageListResponse(Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://package.composite.net/package.asmx")]
    public partial class GetPackageListResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.PackageDescriptor[] GetPackageListResult;

        public GetPackageListResponseBody()
        {
        }

        public GetPackageListResponseBody(Composite.Core.PackageSystem.WebServiceClient.PackageDescriptor[] GetPackageListResult)
        {
            this.GetPackageListResult = GetPackageListResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetEulaTextRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetEulaText", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequestBody Body;

        public GetEulaTextRequest()
        {
        }

        public GetEulaTextRequest(Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://package.composite.net/package.asmx")]
    public partial class GetEulaTextRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public System.Guid eulaId;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string userCulture;

        public GetEulaTextRequestBody()
        {
        }

        public GetEulaTextRequestBody(System.Guid eulaId, string userCulture)
        {
            this.eulaId = eulaId;
            this.userCulture = userCulture;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetEulaTextResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetEulaTextResponse", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponseBody Body;

        public GetEulaTextResponse()
        {
        }

        public GetEulaTextResponse(Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://package.composite.net/package.asmx")]
    public partial class GetEulaTextResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string GetEulaTextResult;

        public GetEulaTextResponseBody()
        {
        }

        public GetEulaTextResponseBody(string GetEulaTextResult)
        {
            this.GetEulaTextResult = GetEulaTextResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RegisterPackageUninstallRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "RegisterPackageUninstall", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequestBody Body;

        public RegisterPackageUninstallRequest()
        {
        }

        public RegisterPackageUninstallRequest(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://package.composite.net/package.asmx")]
    public partial class RegisterPackageUninstallRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public System.Guid InstallationId;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Guid PackageId;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string localUserName;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string localUserIp;

        public RegisterPackageUninstallRequestBody()
        {
        }

        public RegisterPackageUninstallRequestBody(System.Guid InstallationId, System.Guid PackageId, string localUserName, string localUserIp)
        {
            this.InstallationId = InstallationId;
            this.PackageId = PackageId;
            this.localUserName = localUserName;
            this.localUserIp = localUserIp;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RegisterPackageUninstallResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "RegisterPackageUninstallResponse", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponseBody Body;

        public RegisterPackageUninstallResponse()
        {
        }

        public RegisterPackageUninstallResponse(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterPackageUninstallResponseBody
    {

        public RegisterPackageUninstallResponseBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PackageActivityRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PackageActivity", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.PackageActivityRequestBody Body;

        public PackageActivityRequest()
        {
        }

        public PackageActivityRequest(Composite.Core.PackageSystem.WebServiceClient.PackageActivityRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://package.composite.net/package.asmx")]
    public partial class PackageActivityRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public System.Guid installationId;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Guid packageId;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string packageName;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string ip;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public int status;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string exception;

        public PackageActivityRequestBody()
        {
        }

        public PackageActivityRequestBody(System.Guid installationId, System.Guid packageId, string packageName, string ip, int status, string exception)
        {
            this.installationId = installationId;
            this.packageId = packageId;
            this.packageName = packageName;
            this.ip = ip;
            this.status = status;
            this.exception = exception;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PackageActivityResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PackageActivityResponse", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.PackageActivityResponseBody Body;

        public PackageActivityResponse()
        {
        }

        public PackageActivityResponse(Composite.Core.PackageSystem.WebServiceClient.PackageActivityResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PackageActivityResponseBody
    {

        public PackageActivityResponseBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RequestLicenseUpdateRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "RequestLicenseUpdate", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateRequestBody Body;

        public RequestLicenseUpdateRequest()
        {
        }

        public RequestLicenseUpdateRequest(Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://package.composite.net/package.asmx")]
    public partial class RequestLicenseUpdateRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public System.Guid InstallationId;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Guid PackageId;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string localUserName;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string localUserIp;

        public RequestLicenseUpdateRequestBody()
        {
        }

        public RequestLicenseUpdateRequestBody(System.Guid InstallationId, System.Guid PackageId, string localUserName, string localUserIp)
        {
            this.InstallationId = InstallationId;
            this.PackageId = PackageId;
            this.localUserName = localUserName;
            this.localUserIp = localUserIp;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RequestLicenseUpdateResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "RequestLicenseUpdateResponse", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateResponseBody Body;

        public RequestLicenseUpdateResponse()
        {
        }

        public RequestLicenseUpdateResponse(Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://package.composite.net/package.asmx")]
    public partial class RequestLicenseUpdateResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public bool RequestLicenseUpdateResult;

        public RequestLicenseUpdateResponseBody()
        {
        }

        public RequestLicenseUpdateResponseBody(bool RequestLicenseUpdateResult)
        {
            this.RequestLicenseUpdateResult = RequestLicenseUpdateResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RegisterPackageInstallationCompletionRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "RegisterPackageInstallationCompletion", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequestBody Body;

        public RegisterPackageInstallationCompletionRequest()
        {
        }

        public RegisterPackageInstallationCompletionRequest(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://package.composite.net/package.asmx")]
    public partial class RegisterPackageInstallationCompletionRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public System.Guid InstallationId;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Guid PackageId;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string LocalUserName;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string localUserIp;

        public RegisterPackageInstallationCompletionRequestBody()
        {
        }

        public RegisterPackageInstallationCompletionRequestBody(System.Guid InstallationId, System.Guid PackageId, string LocalUserName, string localUserIp)
        {
            this.InstallationId = InstallationId;
            this.PackageId = PackageId;
            this.LocalUserName = LocalUserName;
            this.localUserIp = localUserIp;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RegisterPackageInstallationCompletionResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "RegisterPackageInstallationCompletionResponse", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponseBody Body;

        public RegisterPackageInstallationCompletionResponse()
        {
        }

        public RegisterPackageInstallationCompletionResponse(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterPackageInstallationCompletionResponseBody
    {

        public RegisterPackageInstallationCompletionResponseBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RegisterPackageInstallationFailureRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "RegisterPackageInstallationFailure", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequestBody Body;

        public RegisterPackageInstallationFailureRequest()
        {
        }

        public RegisterPackageInstallationFailureRequest(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://package.composite.net/package.asmx")]
    public partial class RegisterPackageInstallationFailureRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public System.Guid InstallationId;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Guid PackageId;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string LocalUserName;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string localUserIp;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string exceptionString;

        public RegisterPackageInstallationFailureRequestBody()
        {
        }

        public RegisterPackageInstallationFailureRequestBody(System.Guid InstallationId, System.Guid PackageId, string LocalUserName, string localUserIp, string exceptionString)
        {
            this.InstallationId = InstallationId;
            this.PackageId = PackageId;
            this.LocalUserName = LocalUserName;
            this.localUserIp = localUserIp;
            this.exceptionString = exceptionString;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RegisterPackageInstallationFailureResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "RegisterPackageInstallationFailureResponse", Namespace = "http://package.composite.net/package.asmx", Order = 0)]
        public Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponseBody Body;

        public RegisterPackageInstallationFailureResponse()
        {
        }

        public RegisterPackageInstallationFailureResponse(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterPackageInstallationFailureResponseBody
    {

        public RegisterPackageInstallationFailureResponseBody()
        {
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PackagesSoapChannel : Composite.Core.PackageSystem.WebServiceClient.PackagesSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PackagesSoapClient : System.ServiceModel.ClientBase<Composite.Core.PackageSystem.WebServiceClient.PackagesSoap>, Composite.Core.PackageSystem.WebServiceClient.PackagesSoap
    {

        public PackagesSoapClient()
        {
        }

        public PackagesSoapClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public PackagesSoapClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public PackagesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public PackagesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponse Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.GetPackageList(Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequest request)
        {
            return base.Channel.GetPackageList(request);
        }

        public Composite.Core.PackageSystem.WebServiceClient.PackageDescriptor[] GetPackageList(System.Guid InstallationId, string Culture)
        {
            Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.Culture = Culture;
            Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).GetPackageList(inValue);
            return retVal.Body.GetPackageListResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponse> Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.GetPackageListAsync(Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequest request)
        {
            return base.Channel.GetPackageListAsync(request);
        }

        public System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponse> GetPackageListAsync(System.Guid InstallationId, string Culture)
        {
            Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.Culture = Culture;
            return ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).GetPackageListAsync(inValue);
        }

        public bool IsOperational()
        {
            return base.Channel.IsOperational();
        }

        public System.Threading.Tasks.Task<bool> IsOperationalAsync()
        {
            return base.Channel.IsOperationalAsync();
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponse Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.GetEulaText(Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequest request)
        {
            return base.Channel.GetEulaText(request);
        }

        public string GetEulaText(System.Guid eulaId, string userCulture)
        {
            Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequestBody();
            inValue.Body.eulaId = eulaId;
            inValue.Body.userCulture = userCulture;
            Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).GetEulaText(inValue);
            return retVal.Body.GetEulaTextResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponse> Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.GetEulaTextAsync(Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequest request)
        {
            return base.Channel.GetEulaTextAsync(request);
        }

        public System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponse> GetEulaTextAsync(System.Guid eulaId, string userCulture)
        {
            Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequestBody();
            inValue.Body.eulaId = eulaId;
            inValue.Body.userCulture = userCulture;
            return ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).GetEulaTextAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponse Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.RegisterPackageUninstall(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequest request)
        {
            return base.Channel.RegisterPackageUninstall(request);
        }

        public void RegisterPackageUninstall(System.Guid InstallationId, System.Guid PackageId, string localUserName, string localUserIp)
        {
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.PackageId = PackageId;
            inValue.Body.localUserName = localUserName;
            inValue.Body.localUserIp = localUserIp;
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).RegisterPackageUninstall(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponse> Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.RegisterPackageUninstallAsync(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequest request)
        {
            return base.Channel.RegisterPackageUninstallAsync(request);
        }

        public System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponse> RegisterPackageUninstallAsync(System.Guid InstallationId, System.Guid PackageId, string localUserName, string localUserIp)
        {
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.PackageId = PackageId;
            inValue.Body.localUserName = localUserName;
            inValue.Body.localUserIp = localUserIp;
            return ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).RegisterPackageUninstallAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.PackageActivityResponse Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.PackageActivity(Composite.Core.PackageSystem.WebServiceClient.PackageActivityRequest request)
        {
            return base.Channel.PackageActivity(request);
        }

        public void PackageActivity(System.Guid installationId, System.Guid packageId, string packageName, string ip, int status, string exception)
        {
            Composite.Core.PackageSystem.WebServiceClient.PackageActivityRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.PackageActivityRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.PackageActivityRequestBody();
            inValue.Body.installationId = installationId;
            inValue.Body.packageId = packageId;
            inValue.Body.packageName = packageName;
            inValue.Body.ip = ip;
            inValue.Body.status = status;
            inValue.Body.exception = exception;
            Composite.Core.PackageSystem.WebServiceClient.PackageActivityResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).PackageActivity(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.PackageActivityResponse> Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.PackageActivityAsync(Composite.Core.PackageSystem.WebServiceClient.PackageActivityRequest request)
        {
            return base.Channel.PackageActivityAsync(request);
        }

        public System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.PackageActivityResponse> PackageActivityAsync(System.Guid installationId, System.Guid packageId, string packageName, string ip, int status, string exception)
        {
            Composite.Core.PackageSystem.WebServiceClient.PackageActivityRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.PackageActivityRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.PackageActivityRequestBody();
            inValue.Body.installationId = installationId;
            inValue.Body.packageId = packageId;
            inValue.Body.packageName = packageName;
            inValue.Body.ip = ip;
            inValue.Body.status = status;
            inValue.Body.exception = exception;
            return ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).PackageActivityAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateResponse Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.RequestLicenseUpdate(Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateRequest request)
        {
            return base.Channel.RequestLicenseUpdate(request);
        }

        public bool RequestLicenseUpdate(System.Guid InstallationId, System.Guid PackageId, string localUserName, string localUserIp)
        {
            Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.PackageId = PackageId;
            inValue.Body.localUserName = localUserName;
            inValue.Body.localUserIp = localUserIp;
            Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).RequestLicenseUpdate(inValue);
            return retVal.Body.RequestLicenseUpdateResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateResponse> Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.RequestLicenseUpdateAsync(Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateRequest request)
        {
            return base.Channel.RequestLicenseUpdateAsync(request);
        }

        public System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateResponse> RequestLicenseUpdateAsync(System.Guid InstallationId, System.Guid PackageId, string localUserName, string localUserIp)
        {
            Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.RequestLicenseUpdateRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.PackageId = PackageId;
            inValue.Body.localUserName = localUserName;
            inValue.Body.localUserIp = localUserIp;
            return ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).RequestLicenseUpdateAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponse Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.RegisterPackageInstallationCompletion(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequest request)
        {
            return base.Channel.RegisterPackageInstallationCompletion(request);
        }

        public void RegisterPackageInstallationCompletion(System.Guid InstallationId, System.Guid PackageId, string LocalUserName, string localUserIp)
        {
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.PackageId = PackageId;
            inValue.Body.LocalUserName = LocalUserName;
            inValue.Body.localUserIp = localUserIp;
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).RegisterPackageInstallationCompletion(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponse> Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.RegisterPackageInstallationCompletionAsync(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequest request)
        {
            return base.Channel.RegisterPackageInstallationCompletionAsync(request);
        }

        public System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponse> RegisterPackageInstallationCompletionAsync(System.Guid InstallationId, System.Guid PackageId, string LocalUserName, string localUserIp)
        {
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.PackageId = PackageId;
            inValue.Body.LocalUserName = LocalUserName;
            inValue.Body.localUserIp = localUserIp;
            return ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).RegisterPackageInstallationCompletionAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponse Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.RegisterPackageInstallationFailure(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequest request)
        {
            return base.Channel.RegisterPackageInstallationFailure(request);
        }

        public void RegisterPackageInstallationFailure(System.Guid InstallationId, System.Guid PackageId, string LocalUserName, string localUserIp, string exceptionString)
        {
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.PackageId = PackageId;
            inValue.Body.LocalUserName = LocalUserName;
            inValue.Body.localUserIp = localUserIp;
            inValue.Body.exceptionString = exceptionString;
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).RegisterPackageInstallationFailure(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponse> Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.RegisterPackageInstallationFailureAsync(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequest request)
        {
            return base.Channel.RegisterPackageInstallationFailureAsync(request);
        }

        public System.Threading.Tasks.Task<Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponse> RegisterPackageInstallationFailureAsync(System.Guid InstallationId, System.Guid PackageId, string LocalUserName, string localUserIp, string exceptionString)
        {
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.PackageId = PackageId;
            inValue.Body.LocalUserName = LocalUserName;
            inValue.Body.localUserIp = localUserIp;
            inValue.Body.exceptionString = exceptionString;
            return ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).RegisterPackageInstallationFailureAsync(inValue);
        }
    }
}
