//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composite.Core.PackageSystem.WebServiceClient {
    using System.Runtime.Serialization;
    using System;


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PackageDescriptor", Namespace="http://package.composite.net/package.asmx")]
    [System.SerializableAttribute()]
    public partial class PackageDescriptor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechicalDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReadMoreUrlField;
        
        private bool IsTrialField;
        
        private int TrialPeriodDaysField;
        
        private bool IsFreeField;
        
        private bool InstallationRequireLicenseFileUpdateField;
        
        private decimal PriceAmmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceCurrencyField;
        
        private bool UpgradeAgreementMandatoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MinCompositeVersionSupportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaxCompositeVersionSupportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Composite.Core.PackageSystem.WebServiceClient.PackageReference[] RequiredPackagesField;
        
        private System.Guid EulaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageFileDownloadUrlField;
        
        private System.Guid LicenseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CultureField;


        /// <exclude />
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PackageVersion {
            get {
                return this.PackageVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageVersionField, value) != true)) {
                    this.PackageVersionField = value;
                    this.RaisePropertyChanged("PackageVersion");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TechicalDetails {
            get {
                return this.TechicalDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.TechicalDetailsField, value) != true)) {
                    this.TechicalDetailsField = value;
                    this.RaisePropertyChanged("TechicalDetails");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ReadMoreUrl {
            get {
                return this.ReadMoreUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ReadMoreUrlField, value) != true)) {
                    this.ReadMoreUrlField = value;
                    this.RaisePropertyChanged("ReadMoreUrl");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool IsTrial {
            get {
                return this.IsTrialField;
            }
            set {
                if ((this.IsTrialField.Equals(value) != true)) {
                    this.IsTrialField = value;
                    this.RaisePropertyChanged("IsTrial");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int TrialPeriodDays {
            get {
                return this.TrialPeriodDaysField;
            }
            set {
                if ((this.TrialPeriodDaysField.Equals(value) != true)) {
                    this.TrialPeriodDaysField = value;
                    this.RaisePropertyChanged("TrialPeriodDays");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool IsFree {
            get {
                return this.IsFreeField;
            }
            set {
                if ((this.IsFreeField.Equals(value) != true)) {
                    this.IsFreeField = value;
                    this.RaisePropertyChanged("IsFree");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool InstallationRequireLicenseFileUpdate {
            get {
                return this.InstallationRequireLicenseFileUpdateField;
            }
            set {
                if ((this.InstallationRequireLicenseFileUpdateField.Equals(value) != true)) {
                    this.InstallationRequireLicenseFileUpdateField = value;
                    this.RaisePropertyChanged("InstallationRequireLicenseFileUpdate");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public decimal PriceAmmount {
            get {
                return this.PriceAmmountField;
            }
            set {
                if ((this.PriceAmmountField.Equals(value) != true)) {
                    this.PriceAmmountField = value;
                    this.RaisePropertyChanged("PriceAmmount");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string PriceCurrency {
            get {
                return this.PriceCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceCurrencyField, value) != true)) {
                    this.PriceCurrencyField = value;
                    this.RaisePropertyChanged("PriceCurrency");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool UpgradeAgreementMandatory {
            get {
                return this.UpgradeAgreementMandatoryField;
            }
            set {
                if ((this.UpgradeAgreementMandatoryField.Equals(value) != true)) {
                    this.UpgradeAgreementMandatoryField = value;
                    this.RaisePropertyChanged("UpgradeAgreementMandatory");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string MinCompositeVersionSupported {
            get {
                return this.MinCompositeVersionSupportedField;
            }
            set {
                if ((object.ReferenceEquals(this.MinCompositeVersionSupportedField, value) != true)) {
                    this.MinCompositeVersionSupportedField = value;
                    this.RaisePropertyChanged("MinCompositeVersionSupported");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string MaxCompositeVersionSupported {
            get {
                return this.MaxCompositeVersionSupportedField;
            }
            set {
                if ((object.ReferenceEquals(this.MaxCompositeVersionSupportedField, value) != true)) {
                    this.MaxCompositeVersionSupportedField = value;
                    this.RaisePropertyChanged("MaxCompositeVersionSupported");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public Composite.Core.PackageSystem.WebServiceClient.PackageReference[] RequiredPackages {
            get {
                return this.RequiredPackagesField;
            }
            set {
                if ((object.ReferenceEquals(this.RequiredPackagesField, value) != true)) {
                    this.RequiredPackagesField = value;
                    this.RaisePropertyChanged("RequiredPackages");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Guid EulaId {
            get {
                return this.EulaIdField;
            }
            set {
                if ((this.EulaIdField.Equals(value) != true)) {
                    this.EulaIdField = value;
                    this.RaisePropertyChanged("EulaId");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string PackageFileDownloadUrl {
            get {
                return this.PackageFileDownloadUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageFileDownloadUrlField, value) != true)) {
                    this.PackageFileDownloadUrlField = value;
                    this.RaisePropertyChanged("PackageFileDownloadUrl");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Guid LicenseId {
            get {
                return this.LicenseIdField;
            }
            set {
                if ((this.LicenseIdField.Equals(value) != true)) {
                    this.LicenseIdField = value;
                    this.RaisePropertyChanged("LicenseId");
                }
            }
        }


        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Culture {
            get {
                return this.CultureField;
            }
            set {
                if ((object.ReferenceEquals(this.CultureField, value) != true)) {
                    this.CultureField = value;
                    this.RaisePropertyChanged("Culture");
                }
            }
        }


        /// <exclude />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;


        /// <exclude />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PackageReference", Namespace="http://package.composite.net/package.asmx")]
    [System.SerializableAttribute()]
    public partial class PackageReference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;

        /// <exclude />
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }

        /// <exclude />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        /// <exclude />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://package.composite.net/package.asmx", ConfigurationName="ServiceReference1.PackagesSoap")]
    public interface PackagesSoap {

        /// <exclude />
        // CODEGEN: Generating message contract since element name Culture from namespace http://package.composite.net/package.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://package.composite.net/package.asmx/GetPackageList", ReplyAction="*")]
        Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponse GetPackageList(Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequest request);

        /// <exclude />
        [System.ServiceModel.OperationContractAttribute(Action="http://package.composite.net/package.asmx/IsOperational", ReplyAction="*")]
        bool IsOperational();

        /// <exclude />
        // CODEGEN: Generating message contract since element name userCulture from namespace http://package.composite.net/package.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://package.composite.net/package.asmx/GetEulaText", ReplyAction="*")]
        Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponse GetEulaText(Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequest request);

        /// <exclude />
        // CODEGEN: Generating message contract since element name localUserName from namespace http://package.composite.net/package.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://package.composite.net/package.asmx/RegisterPackageUninstall", ReplyAction="*")]
        Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponse RegisterPackageUninstall(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequest request);

        /// <exclude />
        // CODEGEN: Generating message contract since element name LocalUserName from namespace http://package.composite.net/package.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://package.composite.net/package.asmx/RegisterPackageInstallationCompletion", ReplyAction="*")]
        Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponse RegisterPackageInstallationCompletion(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequest request);

        /// <exclude />
        // CODEGEN: Generating message contract since element name LocalUserName from namespace http://package.composite.net/package.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://package.composite.net/package.asmx/RegisterPackageInstallationFailure", ReplyAction="*")]
        Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponse RegisterPackageInstallationFailure(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequest request);
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPackageListRequest {

        /// <exclude />
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPackageList", Namespace="http://package.composite.net/package.asmx", Order=0)]
        public Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequestBody Body;

        /// <exclude />
        public GetPackageListRequest() {
        }

        /// <exclude />
        public GetPackageListRequest(Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequestBody Body) {
            this.Body = Body;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://package.composite.net/package.asmx")]
    public partial class GetPackageListRequestBody {

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid InstallationId;

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Culture;

        /// <exclude />
        public GetPackageListRequestBody() {
        }

        /// <exclude />
        public GetPackageListRequestBody(System.Guid InstallationId, string Culture) {
            this.InstallationId = InstallationId;
            this.Culture = Culture;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPackageListResponse {

        /// <exclude />
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPackageListResponse", Namespace="http://package.composite.net/package.asmx", Order=0)]
        public Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponseBody Body;

        /// <exclude />
        public GetPackageListResponse() {
        }

        /// <exclude />
        public GetPackageListResponse(Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponseBody Body) {
            this.Body = Body;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://package.composite.net/package.asmx")]
    public partial class GetPackageListResponseBody {

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Composite.Core.PackageSystem.WebServiceClient.PackageDescriptor[] GetPackageListResult;

        /// <exclude />
        public GetPackageListResponseBody() {
        }

        /// <exclude />
        public GetPackageListResponseBody(Composite.Core.PackageSystem.WebServiceClient.PackageDescriptor[] GetPackageListResult) {
            this.GetPackageListResult = GetPackageListResult;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEulaTextRequest {

        /// <exclude />
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEulaText", Namespace="http://package.composite.net/package.asmx", Order=0)]
        public Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequestBody Body;

        /// <exclude />
        public GetEulaTextRequest() {
        }

        /// <exclude />
        public GetEulaTextRequest(Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequestBody Body) {
            this.Body = Body;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://package.composite.net/package.asmx")]
    public partial class GetEulaTextRequestBody {

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid eulaId;

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userCulture;

        /// <exclude />
        public GetEulaTextRequestBody() {
        }

        /// <exclude />
        public GetEulaTextRequestBody(System.Guid eulaId, string userCulture) {
            this.eulaId = eulaId;
            this.userCulture = userCulture;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEulaTextResponse {

        /// <exclude />
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEulaTextResponse", Namespace="http://package.composite.net/package.asmx", Order=0)]
        public Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponseBody Body;

        /// <exclude />
        public GetEulaTextResponse() {
        }

        /// <exclude />
        public GetEulaTextResponse(Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponseBody Body) {
            this.Body = Body;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://package.composite.net/package.asmx")]
    public partial class GetEulaTextResponseBody {

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEulaTextResult;

        /// <exclude />
        public GetEulaTextResponseBody() {
        }

        /// <exclude />
        public GetEulaTextResponseBody(string GetEulaTextResult) {
            this.GetEulaTextResult = GetEulaTextResult;
        }
    }



    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPackageUninstallRequest {

        /// <exclude />
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPackageUninstall", Namespace="http://package.composite.net/package.asmx", Order=0)]
        public Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequestBody Body;

        /// <exclude />
        public RegisterPackageUninstallRequest() {
        }

        /// <exclude />
        public RegisterPackageUninstallRequest(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequestBody Body) {
            this.Body = Body;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://package.composite.net/package.asmx")]
    public partial class RegisterPackageUninstallRequestBody {

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid InstallationId;

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid PackageId;

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string localUserName;

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string localUserIp;

        /// <exclude />
        public RegisterPackageUninstallRequestBody() {
        }

        /// <exclude />
        public RegisterPackageUninstallRequestBody(System.Guid InstallationId, System.Guid PackageId, string localUserName, string localUserIp) {
            this.InstallationId = InstallationId;
            this.PackageId = PackageId;
            this.localUserName = localUserName;
            this.localUserIp = localUserIp;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPackageUninstallResponse {

        /// <exclude />
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPackageUninstallResponse", Namespace="http://package.composite.net/package.asmx", Order=0)]
        public Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponseBody Body;

        /// <exclude />
        public RegisterPackageUninstallResponse() {
        }

        /// <exclude />
        public RegisterPackageUninstallResponse(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponseBody Body) {
            this.Body = Body;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterPackageUninstallResponseBody {

        /// <exclude />
        public RegisterPackageUninstallResponseBody() {
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPackageInstallationCompletionRequest {

        /// <exclude />
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPackageInstallationCompletion", Namespace="http://package.composite.net/package.asmx", Order=0)]
        public Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequestBody Body;

        /// <exclude />
        public RegisterPackageInstallationCompletionRequest() {
        }

        /// <exclude />
        public RegisterPackageInstallationCompletionRequest(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequestBody Body) {
            this.Body = Body;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://package.composite.net/package.asmx")]
    public partial class RegisterPackageInstallationCompletionRequestBody {

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid InstallationId;

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid PackageId;

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LocalUserName;

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string localUserIp;

        /// <exclude />
        public RegisterPackageInstallationCompletionRequestBody() {
        }

        /// <exclude />
        public RegisterPackageInstallationCompletionRequestBody(System.Guid InstallationId, System.Guid PackageId, string LocalUserName, string localUserIp) {
            this.InstallationId = InstallationId;
            this.PackageId = PackageId;
            this.LocalUserName = LocalUserName;
            this.localUserIp = localUserIp;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPackageInstallationCompletionResponse {

        /// <exclude />
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPackageInstallationCompletionResponse", Namespace="http://package.composite.net/package.asmx", Order=0)]
        public Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponseBody Body;

        /// <exclude />
        public RegisterPackageInstallationCompletionResponse() {
        }

        /// <exclude />
        public RegisterPackageInstallationCompletionResponse(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponseBody Body) {
            this.Body = Body;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterPackageInstallationCompletionResponseBody {

        /// <exclude />
        public RegisterPackageInstallationCompletionResponseBody() {
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPackageInstallationFailureRequest {

        /// <exclude />
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPackageInstallationFailure", Namespace="http://package.composite.net/package.asmx", Order=0)]
        public Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequestBody Body;

        /// <exclude />
        public RegisterPackageInstallationFailureRequest() {
        }

        /// <exclude />
        public RegisterPackageInstallationFailureRequest(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequestBody Body) {
            this.Body = Body;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://package.composite.net/package.asmx")]
    public partial class RegisterPackageInstallationFailureRequestBody {

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid InstallationId;

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Guid PackageId;

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LocalUserName;

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string localUserIp;

        /// <exclude />
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string exceptionString;

        /// <exclude />
        public RegisterPackageInstallationFailureRequestBody() {
        }

        /// <exclude />
        public RegisterPackageInstallationFailureRequestBody(System.Guid InstallationId, System.Guid PackageId, string LocalUserName, string localUserIp, string exceptionString) {
            this.InstallationId = InstallationId;
            this.PackageId = PackageId;
            this.LocalUserName = LocalUserName;
            this.localUserIp = localUserIp;
            this.exceptionString = exceptionString;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPackageInstallationFailureResponse {

        /// <exclude />
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPackageInstallationFailureResponse", Namespace="http://package.composite.net/package.asmx", Order=0)]
        public Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponseBody Body;

        /// <exclude />
        public RegisterPackageInstallationFailureResponse() {
        }

        /// <exclude />
        public RegisterPackageInstallationFailureResponse(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponseBody Body) {
            this.Body = Body;
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterPackageInstallationFailureResponseBody {

        /// <exclude />
        public RegisterPackageInstallationFailureResponseBody() {
        }
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PackagesSoapChannel : Composite.Core.PackageSystem.WebServiceClient.PackagesSoap, System.ServiceModel.IClientChannel {
    }


    /// <summary>    
    /// </summary>
    /// <exclude />
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)] 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PackagesSoapClient : System.ServiceModel.ClientBase<Composite.Core.PackageSystem.WebServiceClient.PackagesSoap>, Composite.Core.PackageSystem.WebServiceClient.PackagesSoap {

        /// <exclude />
        public PackagesSoapClient() {
        }

        /// <exclude />
        public PackagesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }

        /// <exclude />
        public PackagesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }

        /// <exclude />
        public PackagesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }

        /// <exclude />
        public PackagesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        /// <exclude />
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponse Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.GetPackageList(Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequest request) {
            return base.Channel.GetPackageList(request);
        }

        /// <exclude />
        public Composite.Core.PackageSystem.WebServiceClient.PackageDescriptor[] GetPackageList(System.Guid InstallationId, string Culture) {
            Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.GetPackageListRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.Culture = Culture;
            Composite.Core.PackageSystem.WebServiceClient.GetPackageListResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).GetPackageList(inValue);
            return retVal.Body.GetPackageListResult;
        }

        /// <exclude />
        public bool IsOperational() {
            return base.Channel.IsOperational();
        }

        /// <exclude />
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponse Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.GetEulaText(Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequest request) {
            return base.Channel.GetEulaText(request);
        }

        /// <exclude />
        public string GetEulaText(System.Guid eulaId, string userCulture) {
            Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.GetEulaTextRequestBody();
            inValue.Body.eulaId = eulaId;
            inValue.Body.userCulture = userCulture;
            Composite.Core.PackageSystem.WebServiceClient.GetEulaTextResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).GetEulaText(inValue);
            return retVal.Body.GetEulaTextResult;
        }

        /// <exclude />
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponse Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.RegisterPackageUninstall(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequest request) {
            return base.Channel.RegisterPackageUninstall(request);
        }

        /// <exclude />
        public void RegisterPackageUninstall(System.Guid InstallationId, System.Guid PackageId, string localUserName, string localUserIp) {
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.PackageId = PackageId;
            inValue.Body.localUserName = localUserName;
            inValue.Body.localUserIp = localUserIp;
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageUninstallResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).RegisterPackageUninstall(inValue);
        }

        /// <exclude />
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponse Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.RegisterPackageInstallationCompletion(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequest request) {
            return base.Channel.RegisterPackageInstallationCompletion(request);
        }

        /// <exclude />
        public void RegisterPackageInstallationCompletion(System.Guid InstallationId, System.Guid PackageId, string LocalUserName, string localUserIp) {
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.PackageId = PackageId;
            inValue.Body.LocalUserName = LocalUserName;
            inValue.Body.localUserIp = localUserIp;
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationCompletionResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).RegisterPackageInstallationCompletion(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponse Composite.Core.PackageSystem.WebServiceClient.PackagesSoap.RegisterPackageInstallationFailure(Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequest request) {
            return base.Channel.RegisterPackageInstallationFailure(request);
        }

        /// <exclude />
        public void RegisterPackageInstallationFailure(System.Guid InstallationId, System.Guid PackageId, string LocalUserName, string localUserIp, string exceptionString) {
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequest inValue = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequest();
            inValue.Body = new Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureRequestBody();
            inValue.Body.InstallationId = InstallationId;
            inValue.Body.PackageId = PackageId;
            inValue.Body.LocalUserName = LocalUserName;
            inValue.Body.localUserIp = localUserIp;
            inValue.Body.exceptionString = exceptionString;
            Composite.Core.PackageSystem.WebServiceClient.RegisterPackageInstallationFailureResponse retVal = ((Composite.Core.PackageSystem.WebServiceClient.PackagesSoap)(this)).RegisterPackageInstallationFailure(inValue);
        }
    }
}