//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composite.content.views.relationshipgraph {
    
    
    public partial class ShowRelationshipOrientedGraph {
        
        /// <summary>
        /// Httpheaders1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HttpHeadersControl Httpheaders1;
        
        /// <summary>
        /// Styleloader1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::StyleLoaderControl Styleloader1;
        
        /// <summary>
        /// Scriptloader1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ScriptLoaderControl Scriptloader1;
        
        /// <summary>
        /// RelationshipOrientedGraphPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder RelationshipOrientedGraphPlaceHolder;
    }
}
