//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Composite_content_views_log_log {
    
    /// <summary>
    /// Form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
    
    /// <summary>
    /// Pager control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Composite.Core.WebClient.UiControlLib.Selector Pager;
    
    /// <summary>
    /// DeleteOlderButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Composite.Core.WebClient.UiControlLib.ToolbarButton DeleteOlderButton;
    
    /// <summary>
    /// chkCritical control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Composite.Core.WebClient.UiControlLib.CheckBox chkCritical;
    
    /// <summary>
    /// chkError control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Composite.Core.WebClient.UiControlLib.CheckBox chkError;
    
    /// <summary>
    /// chkWarning control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Composite.Core.WebClient.UiControlLib.CheckBox chkWarning;
    
    /// <summary>
    /// chkInformation control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Composite.Core.WebClient.UiControlLib.CheckBox chkInformation;
    
    /// <summary>
    /// chkVerbose control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Composite.Core.WebClient.UiControlLib.CheckBox chkVerbose;
    
    /// <summary>
    /// LogHolder control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder LogHolder;
    
    /// <summary>
    /// EmptyLabelPlaheHolder control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder EmptyLabelPlaheHolder;

    protected global::System.Web.UI.WebControls.PlaceHolder LogEntriesRemovedPlaceHolder;
    protected global::System.Web.UI.WebControls.Label LogEntriesRemovedLabel;

}
