//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composite.controls.FormsControls.FormUiControlTemplates.DeveloperTools {
    
    
    public partial class FunctionParameterEditor {
        
        /// <summary>
        /// Styleloader1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::StyleLoaderControl Styleloader1;
        
        /// <summary>
        /// Scriptloader1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ScriptLoaderControl Scriptloader1;
        
        /// <summary>
        /// Httpheaders1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HttpHeadersControl Httpheaders1;
        
        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
        /// <summary>
        /// BaloonPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder MessagesPlaceHolder;
        
        /// <summary>
        /// MakeDirtyEventPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder MakeDirtyEventPlaceHolder;
        
        /// <summary>
        /// ctlFeedback control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.Feedback ctlFeedback;
        
        /// <summary>
        /// btnAddNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.Generic btnAddNew;
        
        /// <summary>
        /// btnDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.Generic btnDelete;
        
        /// <summary>
        /// FieldListRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater FieldListRepeater;
        
        /// <summary>
        /// DetailsSplitPanelPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder DetailsSplitPanelPlaceHolder;
        
        /// <summary>
        /// NameField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.DataInput NameField;
        
        /// <summary>
        /// LabelField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.DataInput LabelField;
        
        /// <summary>
        /// HelpField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.TextArea HelpField;
        
        /// <summary>
        /// TypeSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.Selector TypeSelector;
        
        /// <summary>
        /// btnDefaultValueFunctionMarkup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.PostBackDialog btnDefaultValueFunctionMarkup;
        
        /// <summary>
        /// btnTestValueFunctionMarkup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.PostBackDialog btnTestValueFunctionMarkup;
        
        /// <summary>
        /// btnWidgetFunctionMarkup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.PostBackDialog btnWidgetFunctionMarkup;
        
        /// <summary>
        /// PositionField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.Selector PositionField;
    }
}
