//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompositeTypeFieldDesigner {
    
    
    public partial class TypeFieldDesigner {
        
        /// <summary>
        /// BaloonPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder BaloonPlaceHolder;
        
        /// <summary>
        /// MakeDirtyEventPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder MakeDirtyEventPlaceHolder;
        
        /// <summary>
        /// EnterCreateModeButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.ToolbarButton EnterCreateModeButton;
        
        /// <summary>
        /// DeleteButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.ToolbarButton DeleteButton;
        
        /// <summary>
        /// FieldListRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater FieldListRepeater;
        
        /// <summary>
        /// DetailsSplitPanelPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder DetailsSplitPanelPlaceHolder;
        
        /// <summary>
        /// NameField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.DataInput NameField;
        
        /// <summary>
        /// LabelField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.DataInput LabelField;
        
        /// <summary>
        /// HelpField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.DataInput HelpField;
        
        /// <summary>
        /// PositionField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.Selector PositionField;
        
        /// <summary>
        /// TypeSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.Selector TypeSelector;

        /// <summary>
        /// TypeDetailsPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder TypeDetailsPlaceHolder;
        
        /// <summary>
        /// TypeDetailsLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label TypeDetailsLabel;
        
        /// <summary>
        /// TypeDetailsSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.Selector TypeDetailsSelector;
        
        /// <summary>
        /// TypeDetailsOptionalPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder TypeDetailsOptionalPlaceHolder;
        
        /// <summary>
        /// OptionalSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.Selector OptionalSelector;
        
        /// <summary>
        /// btnWidgetFunctionMarkup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.PostBackDialog btnWidgetFunctionMarkup;
        
        /// <summary>
        /// btnValidationRulesFunctionMarkup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.PostBackDialog btnValidationRulesFunctionMarkup;
        
        /// <summary>
        /// IsTitleFieldDateTimeSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.CheckBox IsTitleFieldDateTimeSelector;
        
        /// <summary>
        /// GroupByPriorityField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.Selector GroupByPriorityField;

        /// <summary>
        /// GroupByPriorityField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.Selector TreeOrderingField;
        
        /// <summary>
        /// btnDefaultValueFunctionMarkup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Composite.Core.WebClient.UiControlLib.PostBackDialog btnDefaultValueFunctionMarkup;

        protected global::Composite.Core.WebClient.UiControlLib.Selector lstKeyType;

        protected global::Composite.Core.WebClient.UiControlLib.DataInput txtKeyFieldName;

        protected global::Composite.Core.WebClient.UiControlLib.CheckBox chkShowInDataUrl;

        protected global::System.Web.UI.WebControls.PlaceHolder plhKeyFieldProperties;

        protected global::System.Web.UI.WebControls.PlaceHolder plhFieldProperties;

        protected global::System.Web.UI.WebControls.PlaceHolder plhDataUrl;

        protected global::System.Web.UI.WebControls.PlaceHolder plhAdvancedFieldProperties;

        protected global::Composite.Core.WebClient.UiControlLib.Selector lstDataUrlOrder;

        protected global::Composite.Core.WebClient.UiControlLib.Selector lstDataUrlDateFormat;
    }
}
